config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :chickens, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:update, :show, :new, :create]
  end

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :chicken
end

app/models/chicken.rb
class Chicken < ActiveRecord::Base
  belongs_to :user
  has_many :bookings

   has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

   validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chickens
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @booking = Booking.all
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.save
    redirect_to bookings_path
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  def destroy
    @bookings.delete
    redirect_to bookings_path
  end



private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:????)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :new, :create, :edit, :update, :destroy]

  def index
    @booking = Booking.all
  end

  def show

  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = @chicken.bookings.new(booking_params)
    @booking.save
    redirect_to chicken_booking_path(@chicken, @booking)
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  def destroy
    @bookings.delete
    redirect_to bookings_path
  end



private

  def set_booking
    @chicken = Chicken.find(params[:chicken_id])
  end

  def booking_params
    params.require(:booking).permit(:starts_on, :ends_on, :accepted)
  end
end

app/controllers/chickens_controller.rb
class ChickensController < ApplicationController
  before_action :set_chicken, only: [:show, :edit, :update, :destroy]

  def index

    # @chickens = Chicken.where.not(latitude: nil)
    @chickens = Chicken.all

    # Let's DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(Chicken.where.not(latitude: nil)) do |chicken, marker|
      marker.lat chicken.latitude
      marker.lng chicken.longitude
    end


  end

  def show
  end

  def new
    @chicken = Chicken.new
  end

  def create
    @chicken = Chicken.new(chicken_params)
  if @chicken.save
    redirect_to chickens_path
  else
    render :new
  end
end

  def edit
  end

  def update
    @chicken.update(chicken_params)
    redirect_to chickens_path
  end

  def destroy

    @chickens.destroy
    redirect_to chickens_path
  end



private

  def set_chicken
    @chicken = Chicken.find(params[:id])
  end

  def chicken_params
    params.require(:chicken).permit(:name, :description, :address, :price_per_day, :user, :picture)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/chickens_helper.rb
module ChickensHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Date de location</h1>
      <%= simple_form_for [@chicken, @booking] do |f| %>
    <%= f.input :begins_on, placeholder: "Chicken" %>
    <%= f.input :ends_on %>
    <%= f.input :accepted %>
    <%= f.submit "Je valide", class: "btn btn-primary"  %>
    <% end %>
  </div>
 </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Bravo ma poule !</h1>
      <p> Votre commande a bien été enregistrée</p>

    </div>
  </div>
</div>

app/views/chickens/index.html.erb
<div class="container">
  <div class="row" style="background-color:">
    <div class="col-xs-6">
        <div class="row">
        <% @chickens.each do |chicken| %>
          <div class="col-xs-6">
              <div class="block1">

                <%= image_tag chicken.picture.url(:medium) if chicken.picture? %>
                <%= chicken.name %>
                <%= chicken.description %>
                <%= chicken.address %>
                <%= chicken.price_per_day %>
                 <%= link_to "je loue", new_chicken_booking_path(chicken) %>

              </div>

          </div>
        <% end %>
        </div>

    </div>

    <div class="col-xs-6" >
      <div id="map"></div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>

app/views/chickens/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>New Chicken</h1>
      <%= simple_form_for(@chicken) do |f| %>
    <%= f.input :name, placeholder: "Chicken" %>
    <%= f.input :description %>
    <%= f.input :price_per_day, placeholder: "15€" %>
    <%= f.input :picture %>
    <%= f.submit "add a chicken", class: "btn btn-primary"  %>



    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <script src="//maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
    <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner text-center" style="background-image: url('http://3.bp.blogspot.com/-Oqm5RD222Aw/T9xWXLdW3dI/AAAAAAAACaM/vszwIbQNUYo/s1600/Chicken+Pictures.jpg')">

  <div class="banner-shadow"></div>
  <div class="banner-content fade-and-slide">
    <h1>Salut ma poule </h1>

      <div id="searchbar">
      <form action="/chickens" method="get" class="mega-search-bar">
       <input type="date" class='datepicker' value="2015-11-06" name="checkin">
       <input type="date" class='datepicker' value="2015-12-06" name="checkout">
       <input type="hidden" id="my_hidden_input">
        <input class="champ" type="text" placeholder="Ou voulez-vous aller ?" name="destination">
       <button type="submit" class="btn">Search</button>
      </form>


      </div>

    <%= link_to t(".top_call_to_action", default: "add a chicken"), new_chicken_path , class: "navbar-wagon-item navbar-wagon-button btn" %>

  </div>
</div>



</div>





</div>



<footer >
   <div class="col-sm-7 col-xs-12 footer-block">
        <h6>
          Suivez notre actualité sur les réseaux sociaux
          <ul class="list-inline social text-center inline-block" id="social-buttons-list">
            <li>
              <a href="https://www.facebook.com/pages/RMP/1422248518078090">
              <i class="fa fa-facebook"></i>
              </a>
            </li>
            <li>
              <a href="https://twitter.com/RMP">
              <i class="fa fa-twitter"></i>
              </a>
            </li>
            <li>
              <a href="https://www.youtube.com/watch?v=mcNQEV6Tduo">
              <i class="fa fa-youtube"></i>
              </a>
            </li>
            <li>
              <a href="https://www.pinterest.com/RMP/">
                <i class="fa fa-pinterest"></i>
              </a>
            </li>
            <li>
              <a href="http://instagram.com/RMP?ref=badge">
                <i class="fa fa-instagram"></i>
              </a>
            </li>
          </ul>
        </h6>
      </div>

</div>




</div></footer>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <a href="/">
      <%= image_tag "https://files.slack.com/files-pri/T02NE0241-F0DRQ0H1C/lapoulette-logo3.png" %>
    </a>

    <div class="navbar-wagon-pusher"></div>

    <form action="" class="navbar-wagon-search hidden-xs hidden-sm">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
    <hr class="hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>
        <div class="icon-badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="icon-badge icon-badge-blue">3</div>
        </div>
      <% end %>
      <hr>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <hr>
      <%= link_to t(".sign_in", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</nav>